const fs = require("fs");
const path = require("path");

// ─── Load pre-computed embeddings (generated by RAG/ingestion_pipeline.py) ────
// Cached across warm Lambda invocations on Vercel.
let CHUNKS = null;

function getChunks() {
  if (!CHUNKS) {
    try {
      const p = path.join(__dirname, "vectorstore.json");
      CHUNKS = JSON.parse(fs.readFileSync(p, "utf-8"));
    } catch {
      CHUNKS = []; // fall through to keyword router if JSON not yet generated
    }
  }
  return CHUNKS;
}

// ─── Vector math ───────────────────────────────────────────────────────────────
function cosineSimilarity(a, b) {
  let dot = 0, na = 0, nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na  += a[i] * a[i];
    nb  += b[i] * b[i];
  }
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

async function embedQuery(query, apiKey) {
  const res = await fetch("https://api.openai.com/v1/embeddings", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({ model: "text-embedding-3-small", input: query }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error?.message || "Embedding request failed");
  return data.data[0].embedding;
}

function retrieveTopChunks(queryVec, chunks, k = 4) {
  return chunks
    .map((c) => ({ text: c.text, score: cosineSimilarity(queryVec, c.embedding) }))
    .sort((a, b) => b.score - a.score)
    .slice(0, k)
    .map((c) => c.text);
}

// ─── System prompt ─────────────────────────────────────────────────────────────
const SYSTEM_PROMPT = `You are a portfolio assistant speaking as Samiur Rahman.

Rules you must follow without exception:
1. Only answer questions about Samiur — education, internships, projects, skills, career goals, and contact info.
2. If the question is not about Samiur (e.g. weather, math, writing code, other people), reply exactly:
   "I can only answer questions about Samiur Rahman. Try asking about his internships, projects, or skills."
3. Answer in first person, 2–4 sentences, no bullet points or headers.
4. Base your answer solely on the resume context provided. Do not fabricate facts.
5. Questions about future plans, career goals, or desired roles are valid — answer from context.

Resume context (retrieved from resume):
{context}`;

// ─── Keyword router — fallback when OpenAI is unavailable ─────────────────────
const KNOWLEDGE_BASE = [
  {
    topics: ["figure", "ota", "connectivity", "slack", "jira", "robot", "hil automation", "embedded automation"],
    answer: "At Figure I scaled OTA and HIL connectivity test automation, growing automated OTA coverage and significantly reducing OTA-related failures. I also built a Slack-Jira integration bot to automate issue triaging and status syncing across the firmware team, and improved HIL reporting pipelines for robot connectivity validation.",
  },
  {
    topics: ["tesla", "sil", "model y", "can bus", "rpm", "dog mode", "child mode", "thermal", "powertrain"],
    answer: "At Tesla I developed SIL/HIL firmware validation test suites for next-gen Model Y powertrain systems. I achieved ±2% motor RPM accuracy through CAN bus monitoring and closed-loop automation, and designed thermal safety tests covering edge cases like Dog Mode and Child Mode.",
  },
  {
    topics: ["tektronix", "scpi", "visa", "instrument", "oscilloscope", "measurement", "json-rpc", "mcp server"],
    answer: "At Tektronix I built MCP servers with JSON-RPC and SCPI/VISA integration for programmatic instrument control. I also developed an AI agent that translates natural-language test goals into automated measurement workflows, bridging LLM reasoning with hardware test equipment.",
  },
  {
    topics: ["citadel", "flutter", "dart", "garage", "websocket", "firebase", "iot app"],
    answer: "At Citadel Technologies I built a Flutter IoT garage control app with real-time WebSocket communication, Firebase push notifications, and REST APIs for secure remote access.",
  },
  {
    topics: ["cache", "l1", "l2", "victim cache", "amat", "hit rate", "miss rate", "cache simulator"],
    answer: "My Cache Simulator models configurable L1, victim, and L2 caches with trace-driven hit/miss rate analysis and AMAT statistics — built in C.",
  },
  {
    topics: ["gpu", "cuda", "image filter", "convolution", "parallel", "thread", "ece 4122"],
    answer: "My GPU Image Filter Engine applies convolution filters in parallel using 10,000+ CUDA threads — built in C++/CUDA for ECE 4122.",
  },
  {
    topics: ["memory allocator", "malloc", "heap", "free", "coalescing", "first-fit", "best-fit"],
    answer: "I built a custom heap memory allocator in C implementing first-fit and best-fit allocation strategies with block coalescing.",
  },
  {
    topics: ["arcade", "fpga", "vga", "binary game", "verilog", "systemverilog"],
    answer: "I built a binary arcade game on FPGA hardware with VGA display output, written in Verilog/SystemVerilog.",
  },
  {
    topics: ["georgia tech", "gatech", "gt", "gpa", "degree", "computer engineering", "dean's list", "graduation", "concentration", "major", "coursework"],
    answer: "I'm studying Computer Engineering at Georgia Tech with a 3.7 GPA and Dean's List recognition, graduating in December 2026.",
  },
  {
    topics: ["python", "c++", "rust", "swift", "javascript", "typescript", "languages", "programming language"],
    answer: "My primary languages are C, C++, Python, and Rust for systems work, plus CUDA for GPU programming, Dart/Flutter for mobile, and JavaScript/TypeScript/React for web.",
  },
  {
    topics: ["embedded", "firmware", "rtos", "i2c", "spi", "uart", "arm", "microcontroller", "hardware"],
    answer: "I have hands-on embedded experience from Figure and Tesla — firmware validation, HIL/SIL testing, CAN bus, SCPI/VISA, and low-level hardware protocols.",
  },
  {
    topics: ["systems", "os", "kernel", "operating system", "architecture", "distributed", "performance"],
    answer: "My systems background spans computer architecture, OS internals, memory management, and distributed systems — through GT coursework and projects like my cache simulator, memory allocator, and GPU engine.",
  },
  {
    topics: ["ai", "machine learning", "ml", "langchain", "openai", "agent", "mcp", "pinecone", "llm", "rag"],
    answer: "I've built AI agents and MCP tooling at Tektronix, worked with LangChain, OpenAI, and vector databases, and built this portfolio's RAG-powered chat. My focus is grounded, task-specific AI.",
  },
  {
    topics: ["contact", "email", "reach", "hire", "get in touch", "linkedin", "github", "recruiter"],
    answer: "You can reach me at srahman96@gatech.edu, connect on LinkedIn at linkedin.com/in/samiur-rahman-1a09b6271, or find my GitHub at github.com/Samiurr10.",
  },
  {
    topics: ["goal", "future", "career", "looking for", "next role", "interest", "after graduation", "full time", "new grad"],
    answer: "I'm graduating in December 2026 and looking for full-time roles in embedded systems, firmware, systems software, or AI/automation engineering.",
  },
  {
    topics: ["who", "about", "introduce", "summary", "background", "tell me", "samiur", "yourself"],
    answer: "I'm Samiur Rahman, a Computer Engineering student at Georgia Tech (GPA 3.7, Dean's List, Dec 2026) with internships at Figure, Tesla, Tektronix, and Citadel.",
  },
];

const ALL_SIGNAL_WORDS = [
  ...new Set(KNOWLEDGE_BASE.flatMap((e) => e.topics)),
  "skill", "project", "intern", "work", "experience", "hire", "background",
  "resume", "portfolio", "degree", "job", "role", "position", "company",
];

function isOffTopic(query) {
  return !ALL_SIGNAL_WORDS.some((w) => query.includes(w));
}

function keywordFallback(query) {
  if (isOffTopic(query)) {
    return "I can only answer questions about Samiur Rahman. Try asking about his internships, projects, or skills.";
  }
  let best = null, bestScore = 0;
  for (const entry of KNOWLEDGE_BASE) {
    const score = entry.topics.filter((t) => query.includes(t)).length;
    if (score > bestScore) { bestScore = score; best = entry; }
  }
  return best
    ? best.answer
    : "I'm Samiur Rahman — Computer Engineering @ Georgia Tech, with internships at Figure, Tesla, Tektronix, and Citadel. Ask about a specific role, project, or skill.";
}

// ─── Vercel serverless handler ────────────────────────────────────────────────
module.exports = async (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") {
    return res.status(405).json({ status: 405, response: "Method not allowed" });
  }

  const { query } = req.body || {};
  const trimmed = String(query || "").trim();

  if (trimmed === "__debug") {
    const chunks = getChunks();
    return res.status(200).json({
      status: 200,
      hasKey: !!process.env.OPENAI_API_KEY,
      keyLength: process.env.OPENAI_API_KEY?.length || 0,
      embeddingsLoaded: chunks.length > 0,
      chunkCount: chunks.length,
      model: "gpt-4o-mini",
      embeddingModel: "text-embedding-3-small",
    });
  }

  if (!trimmed) {
    return res.status(400).json({ status: 400, response: "Please enter a question." });
  }

  const apiKey = process.env.OPENAI_API_KEY;

  // ── RAG path ─────────────────────────────────────────────────────────────────
  if (apiKey) {
    const chunks = getChunks();

    try {
      // Step 1: embed the query
      const queryVec = await embedQuery(trimmed, apiKey);

      // Step 2: retrieve top-5 most relevant resume chunks
      const topChunks = chunks.length > 0
        ? retrieveTopChunks(queryVec, chunks, 5)
        : ["(no resume context available — please run ingestion_pipeline.py)"];

      const context = topChunks.join("\n\n---\n\n");
      const systemMsg = SYSTEM_PROMPT.replace("{context}", context);

      // Step 3: generate answer grounded in retrieved context
      const openaiRes = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          messages: [
            { role: "system", content: systemMsg },
            { role: "user", content: trimmed },
          ],
          max_tokens: 200,
          temperature: 0.2,
        }),
      });

      const data = await openaiRes.json();

      if (openaiRes.ok) {
        const text = data.choices?.[0]?.message?.content?.trim();
        if (text) {
          return res.status(200).json({
            status: 200,
            response: text,
            source: "rag",
            chunksUsed: topChunks.length,
          });
        }
      } else {
        console.error("OpenAI error:", openaiRes.status, JSON.stringify(data));
        return res.status(200).json({
          status: 200,
          response: keywordFallback(trimmed.toLowerCase()),
          source: "fallback",
          llmError: data.error?.message || `HTTP ${openaiRes.status}`,
        });
      }
    } catch (err) {
      console.error("RAG error:", err.message);
    }
  }

  // ── Keyword fallback ─────────────────────────────────────────────────────────
  return res.status(200).json({
    status: 200,
    response: keywordFallback(trimmed.toLowerCase()),
    source: "fallback",
  });
};
